meta_product_name: "Bild"
meta_title: "Bild - Connecting you with construction work"
meta_description: "Bild is a platform that seamlessly connects workers with nearby jobs eliminating expensive, time-consuming and money-grabbing recruitment companies."
meta_image: "banner-resize.jpg" # should exist in `app/assets/images/`

